name: Run integration tests on PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ '17', '21' ]
    runs-on: ${{ matrix.os }}
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Execute Gradle build
        run: ./gradlew --stacktrace --info check

      - name: Build jar for publishing
        run: ./gradlew clean -xtest assemble publishToMavenLocal

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml
          check_name: Test Results with Java ${{ matrix.java }}